import { AppLanguage } from '../store/usePreferencesStore';

export const copy = {
  en: {
    navbar: {
      brandSubtitle: 'Visual Art Detection',
      home: 'Home',
      about: 'About',
      login: 'Login',
      register: 'Register',
      classifier: 'Classifier',
      history: 'History',
      themeToggle: 'Toggle dark mode',
      languageLabel: 'Language',
      english: 'EN',
      tamil: 'TA',
      hindi: 'HI',
    },
    footer: '© 2026 RealLens AI. All rights reserved.',
    home: {
      badge: 'Deepfake Detection Platform',
      title: 'Deepfakes in Visual Art',
      description: 'Differentiating AI-generated art from human art using advanced Convolutional Neural Networks (CNN). Upload an artwork to analyze its structural features and authenticity.',
      startAnalysis: 'Start Analysis',
      viewRecentResults: 'View Recent Results',
      highlights: [
        { label: 'Focus', value: 'AI vs Human Art' },
        { label: 'Method', value: 'CNN-based Analysis' },
        { label: 'Workflow', value: 'Upload, Review, Compare' },
      ],
      aboutTitle: 'About This Website',
      aboutBody: 'This platform is built to examine how AI-generated artworks differ from human-created pieces. It combines image upload, CNN-based prediction, artifact inspection, saved classification history, and an assistant for project guidance in one research-focused workflow.',
      featureCards: [
        { title: 'Authenticity', desc: 'Detect structural artifacts unique to generative models.' },
        { title: 'Artistic Analysis', desc: 'Analyze brushstrokes, texture flow, and composition consistency in visual artworks.' },
        { title: 'CNN Powered', desc: 'Use deep neural feature extraction to separate human-made art from synthetic outputs.' },
        { title: 'Easy Upload', desc: 'Upload JPG, PNG, or WEBP artwork files and start analysis with a simple drag-and-drop workflow.' },
        { title: 'Artifact Detection', desc: 'Inspect repeated patterns, sharp transitions, and image anomalies often found in generated content.' },
        { title: 'Smart Prediction', desc: 'Generate an AI or Human classification result with a confidence score for each submitted image.' },
        { title: 'Recent History', desc: 'Review saved classification results, timestamps, and file names from your latest analyses.' },
        { title: 'AI Assistant', desc: 'Ask project-related questions about deepfakes, CNN methods, and the ethics of AI-generated art.' },
      ],
      classifier: {
        badge: 'Analysis Studio',
        title: 'Art Classifier',
        description: 'Upload an image to begin neural analysis and compare visual signals associated with human-made and AI-generated artworks. The classifier inspects texture behavior, repeated motifs, edge consistency, and artifact patterns.',
        statCards: [
          { label: 'Accepted Files', value: 'JPG, PNG, WEBP' },
          { label: 'Model Focus', value: 'CNN Feature Signals' },
          { label: 'Output', value: 'Prediction + Confidence' },
        ],
        infoCards: [
          { title: 'Authenticity Signals', desc: 'Brush rhythm, texture continuity, and structural realism are compared against known synthetic cues.' },
          { title: 'Research Workflow', desc: 'Upload, inspect, predict, and compare results through one guided classifier panel.' },
        ],
        noteTitle: 'Classifier Note',
        noteBody: 'Best results come from clear artwork images with visible texture and minimal compression noise. Higher-quality inputs produce more meaningful confidence scores.',
      },
      clearHistoryTitle: 'Clear classification history?',
      clearHistoryDescription: 'This removes every recent classification from the saved history and cannot be undone.',
      clearHistoryConfirm: 'Clear history',
      clearHistoryCancel: 'Keep history',
    },
    upload: {
      title: 'Drop your artwork here',
      support: 'Supports JPG, PNG, WEBP. Best with clear artwork images up to 10MB.',
      chooseImage: 'Choose Image',
      chips: ['Canvas texture', 'Brushstroke flow', 'Edge artifacts'],
      processingTitle: 'Neural Feature Extraction...',
      processingBody: 'Analyzing brushstrokes, contours, and synthetic artifact signals',
      complete: 'Analysis Complete',
      failed: 'Upload Failed',
      invalidType: 'Invalid file type. Please upload a JPG, PNG, or WEBP image.',
      largeFile: 'File is too large. Maximum size is 10MB.',
    },
    history: {
      title: 'Recent Classifications',
      subtitle: 'Review the latest artwork analyses, confidence levels, and prediction patterns in one place.',
      empty: 'No history yet. Start by uploading an artwork.',
      confidence: 'Confidence',
      resetLabel: 'Reset classification history',
      total: 'Total Items',
      aiCount: 'AI Results',
      humanCount: 'Human Results',
      latest: 'Latest Run',
      fileLabel: 'File',
      analyzedOn: 'Analyzed',
    },
    result: {
      uploadedFile: 'Uploaded File',
      summary: 'Summary',
      analyzedAt: 'Analyzed At',
      confidenceScore: 'Confidence Score',
      sectionTitle: 'CNN Analysis Result',
      aiSummary: 'Synthetic characteristics detected',
      humanSummary: 'Human-made characteristics detected',
      fallbackLabel: 'Fallback local analysis',
      aiExplanation: 'The classifier found recurring synthetic patterns and distribution cues typically associated with generated imagery.',
      humanExplanation: 'The classifier found irregular texture and organic detail variations that align more closely with human-made artwork.',
      technicalNote: 'Technical Note:',
      systemNote: 'System Note:',
      resultReady: 'Classification Result Ready',
      analysisComplete: 'Analysis Complete',
      file: 'File:',
      timestamp: 'Timestamp:',
    },
    aboutPage: {
      badge: 'About The Model',
      title: 'How the CNN Art Detection Pipeline Works',
      intro: 'This page explains the model thinking behind the classifier, from image intake to feature extraction and final prediction. It is designed for academic presentation as well as user understanding.',
      architectureTitle: 'CNN Architecture Overview',
      architectureBody: 'The classifier follows a staged visual-analysis pipeline that emphasizes texture, composition, and artifact patterns often used to distinguish AI-generated art from human-created work.',
      architectureLayers: [
        { title: 'Input Layer', desc: 'Receives the uploaded artwork image and normalizes visual information for analysis.' },
        { title: 'Convolution Blocks', desc: 'Extract local visual features such as edges, textures, and repeated structures.' },
        { title: 'Pooling Stages', desc: 'Compress spatial detail while preserving important patterns that reflect style and coherence.' },
        { title: 'Dense Prediction Layer', desc: 'Combines learned signals and produces a final classification with confidence.' },
      ],
      stepsTitle: 'How It Works',
      steps: [
        'Upload an artwork image through the classifier panel.',
        'The system validates the file type and prepares the image for analysis.',
        'Visual features such as texture continuity, edge behavior, and repetition are inspected.',
        'The classifier estimates whether the image is AI-generated or human-created.',
        'The final result is displayed with confidence and saved to recent history.',
      ],
      stackTitle: 'Tech Stack',
      stack: [
        'React + TypeScript for the frontend application structure.',
        'Tailwind CSS for interface styling and responsive layout.',
        'Motion for interface animation and transitions.',
        'Express + Multer for API routing and image upload handling.',
        'Better SQLite3 for prediction history storage.',
        'Gemini API with local fallback logic for image classification output.',
      ],
    },
  },
  ta: {
    navbar: {
      brandSubtitle: 'காட்சி கலை கண்டறிதல்',
      home: 'முகப்பு',
      about: 'பற்றி',
      login: 'உள்நுழை',
      register: 'பதிவு செய்',
      classifier: 'வகைப்படுத்தி',
      history: 'வரலாறு',
      themeToggle: 'இருள் நிலையை மாற்று',
      languageLabel: 'மொழி',
      english: 'EN',
      tamil: 'த',
      hindi: 'हि',
    },
    footer: '© 2026 RealLens AI. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    home: {
      badge: 'டீப்‌ஃபேக் கண்டறிதல் தளம்',
      title: 'காட்சி கலையில் டீப்‌ஃபேக்குகள்',
      description: 'மேம்பட்ட கான்வலூஷனல் நியூரல் நெட்வொர்க் (CNN) மூலம் AI உருவாக்கிய கலை மற்றும் மனிதர் உருவாக்கிய கலைவை வேறுபடுத்துகிறது. ஒரு கலைப் படத்தைப் பதிவேற்றி அதன் அமைப்பு மற்றும் உண்மை தன்மையை ஆய்வு செய்யுங்கள்.',
      startAnalysis: 'ஆய்வை தொடங்கு',
      viewRecentResults: 'சமீப முடிவுகள்',
      highlights: [
        { label: 'கவனம்', value: 'AI மற்றும் மனித கலை' },
        { label: 'முறை', value: 'CNN அடிப்படையிலான ஆய்வு' },
        { label: 'செயல்முறை', value: 'பதிவேற்று, மதிப்பீடு, ஒப்பிடு' },
      ],
      aboutTitle: 'இந்த தளத்தைப் பற்றி',
      aboutBody: 'இந்த தளம் AI உருவாக்கிய கலை மற்றும் மனிதர் உருவாக்கிய கலை இடையிலான வேறுபாடுகளை ஆய்வு செய்ய உருவாக்கப்பட்டுள்ளது. இது பட பதிவேற்றம், CNN அடிப்படையிலான கணிப்பு, குறைபாடு ஆய்வு, சேமிக்கப்பட்ட வரலாறு மற்றும் திட்ட உதவியாளரை ஒரே பணிச்சூழலில் இணைக்கிறது.',
      featureCards: [
        { title: 'உண்மை தன்மை', desc: 'உருவாக்கும் மாதிரிகளுக்கே உரிய அமைப்பு குறிகளை கண்டறிகிறது.' },
        { title: 'கலை ஆய்வு', desc: 'படர்த்தல், உரைநடை ஓட்டம், வடிவமைப்பு ஒற்றுமையை ஆய்வு செய்கிறது.' },
        { title: 'CNN இயக்கம்', desc: 'மனிதர் கலை மற்றும் செயற்கை உருவாக்கங்களைக் பிரிக்க ஆழ்ந்த நியூரல் அம்சங்களைப் பயன்படுத்துகிறது.' },
        { title: 'எளிய பதிவேற்றம்', desc: 'JPG, PNG, WEBP கோப்புகளை எளிய drag-and-drop முறையில் பதிவேற்றலாம்.' },
        { title: 'குறைபாடு கண்டறிதல்', desc: 'மீண்டும் வரும் வடிவங்கள், கூர்மையான மாற்றங்கள் மற்றும் செயற்கை குறிகளை ஆய்வு செய்கிறது.' },
        { title: 'செயல்முறை கணிப்பு', desc: 'ஒவ்வொரு படத்திற்கும் AI அல்லது மனிதம் என்ற முடிவை நம்பகத்தன்மையுடன் காட்டுகிறது.' },
        { title: 'சமீப வரலாறு', desc: 'சமீப ஆய்வுகளின் முடிவுகள், நேரம் மற்றும் கோப்பு பெயர்களைக் காணலாம்.' },
        { title: 'AI உதவியாளர்', desc: 'டீப்‌ஃபேக், CNN முறைகள் மற்றும் AI கலை நெறிமுறைகள் பற்றிய கேள்விகளை கேளுங்கள்.' },
      ],
      classifier: {
        badge: 'ஆய்வு நிலையம்',
        title: 'கலை வகைப்படுத்தி',
        description: 'மனிதர் உருவாக்கிய மற்றும் AI உருவாக்கிய கலைக்கிடையிலான காட்சி அம்சங்களை ஒப்பிட படத்தைப் பதிவேற்றுங்கள். இது உரைநடை, மீள்தோற்றங்கள், விளிம்பு ஒற்றுமை மற்றும் குறைபாடுகளை ஆய்வு செய்கிறது.',
        statCards: [
          { label: 'ஏற்கப்படும் கோப்புகள்', value: 'JPG, PNG, WEBP' },
          { label: 'மாதிரி கவனம்', value: 'CNN அம்ச சிக்னல்கள்' },
          { label: 'வெளியீடு', value: 'முடிவு + நம்பகத்தன்மை' },
        ],
        infoCards: [
          { title: 'உண்மை குறிகள்', desc: 'தூரிகை ஓட்டம், உரைநடை தொடர்ச்சி மற்றும் அமைப்பு நிஜத்தன்மை செயற்கை குறிகளுடன் ஒப்பிடப்படுகிறது.' },
          { title: 'ஆய்வு பணிச்சூழல்', desc: 'பதிவேற்று, ஆய்வு செய், கணிப்பு பெறு, முடிவுகளை ஒப்பிடு.' },
        ],
        noteTitle: 'வகைப்படுத்தி குறிப்பு',
        noteBody: 'தெளிவான உரைநடை கொண்ட உயர் தர படங்கள் சிறந்த முடிவுகளை தரும். நல்ல தரம் அதிக நம்பகத்தன்மை மதிப்பை வழங்கும்.',
      },
      clearHistoryTitle: 'வகைப்படுத்தல் வரலாற்றை நீக்கவா?',
      clearHistoryDescription: 'இது அனைத்து சமீப வரலாற்றையும் நீக்கும். இதை மீண்டும் பெற முடியாது.',
      clearHistoryConfirm: 'வரலாறு நீக்கு',
      clearHistoryCancel: 'வைத்திரு',
    },
    upload: {
      title: 'உங்கள் கலைப்படத்தை இங்கே விடுங்கள்',
      support: 'JPG, PNG, WEBP ஆதரவு. 10MB வரை தெளிவான கலைப் படங்கள் சிறந்தவை.',
      chooseImage: 'படத்தைத் தேர்வு செய்',
      chips: ['கேன்வாஸ் உரைநடை', 'தூரிகை ஓட்டம்', 'விளிம்பு குறிகள்'],
      processingTitle: 'நியூரல் அம்ச ஆய்வு...',
      processingBody: 'தூரிகை கோடுகள், வடிவ வரைகள் மற்றும் செயற்கை குறிகளை ஆய்வு செய்கிறது',
      complete: 'ஆய்வு முடிந்தது',
      failed: 'பதிவேற்றம் தோல்வி',
      invalidType: 'தவறான கோப்பு வகை. JPG, PNG, WEBP மட்டும் பதிவேற்றவும்.',
      largeFile: 'கோப்பு மிகவும் பெரியது. அதிகபட்சம் 10MB மட்டுமே.',
    },
    history: {
      title: 'சமீப வகைப்படுத்தல்கள்',
      subtitle: 'சமீப கலை ஆய்வுகள், நம்பகத்தன்மை அளவுகள் மற்றும் முடிவு போக்குகளை ஒரே இடத்தில் பாருங்கள்.',
      empty: 'இன்னும் வரலாறு இல்லை. முதலில் ஒரு கலைப்படத்தைப் பதிவேற்றுங்கள்.',
      confidence: 'நம்பகத்தன்மை',
      resetLabel: 'வகைப்படுத்தல் வரலாற்றை நீக்கு',
      total: 'மொத்த உருப்படிகள்',
      aiCount: 'AI முடிவுகள்',
      humanCount: 'மனித முடிவுகள்',
      latest: 'சமீப இயக்கம்',
      fileLabel: 'கோப்பு',
      analyzedOn: 'ஆய்வு நேரம்',
    },
    result: {
      uploadedFile: 'பதிவேற்றப்பட்ட கோப்பு',
      summary: 'சுருக்கம்',
      analyzedAt: 'ஆய்வு செய்யப்பட்ட நேரம்',
      confidenceScore: 'நம்பகத்தன்மை மதிப்பு',
      sectionTitle: 'CNN ஆய்வு முடிவு',
      aiSummary: 'செயற்கை அம்சங்கள் கண்டறியப்பட்டன',
      humanSummary: 'மனித உருவாக்க அம்சங்கள் கண்டறியப்பட்டன',
      fallbackLabel: 'உள்ளூர் மாற்று ஆய்வு',
      aiExplanation: 'மீண்டும் வரும் செயற்கை வடிவங்கள் மற்றும் பகிர்வு குறிகள் கண்டறியப்பட்டன.',
      humanExplanation: 'இயல்பான உரைநடை மற்றும் இயற்கை வேறுபாடுகள் மனிதர் கலைக்குச் சேர்ந்தவையாக காணப்பட்டன.',
      technicalNote: 'தொழில்நுட்ப குறிப்பு:',
      systemNote: 'கணினி குறிப்பு:',
      resultReady: 'வகைப்படுத்தல் முடிவு தயாராக உள்ளது',
      analysisComplete: 'ஆய்வு முடிந்தது',
      file: 'கோப்பு:',
      timestamp: 'நேரம்:',
    },
    aboutPage: {
      badge: 'மாதிரி விளக்கம்',
      title: 'CNN கலை கண்டறிதல் செயன்முறை எப்படி செயல்படுகிறது',
      intro: 'இந்த பக்கம், படம் பதிவேற்றம் முதல் அம்சப் பிடித்தல் மற்றும் இறுதி கணிப்பு வரை வகைப்படுத்தி எவ்வாறு செயல்படுகிறது என்பதை விளக்குகிறது. இது கல்வி மற்றும் பயனர் புரிதலுக்காக வடிவமைக்கப்பட்டது.',
      architectureTitle: 'CNN கட்டமைப்பு பார்வை',
      architectureBody: 'இந்த வகைப்படுத்தி, உரைநடை, அமைப்பு மற்றும் செயற்கை குறிகளை மையமாகக் கொண்ட கட்டடுத்த காட்சி ஆய்வு நடைமுறையை பின்பற்றுகிறது.',
      architectureLayers: [
        { title: 'உள்ளீட்டு அடுக்கு', desc: 'பதிவேற்றப்பட்ட கலைப்படத்தைப் பெற்று காட்சி தரவை ஒழுங்குபடுத்துகிறது.' },
        { title: 'Convolution கட்டங்கள்', desc: 'விளிம்புகள், உரைநடை மற்றும் மீண்டும் வரும் வடிவங்களைப் பிடிக்கிறது.' },
        { title: 'Pooling கட்டங்கள்', desc: 'முக்கிய அம்சங்களை வைத்துக் கொண்டு பரப்பளவு தகவலைச் சுருக்குகிறது.' },
        { title: 'Dense கணிப்பு அடுக்கு', desc: 'கற்ற அம்சங்களை இணைத்து இறுதி வகைப்படுத்தலை வழங்குகிறது.' },
      ],
      stepsTitle: 'செயல்முறை',
      steps: [
        'வகைப்படுத்தி பகுதியில் கலைப்படத்தைப் பதிவேற்றுங்கள்.',
        'கோப்பு வகை சரிபார்க்கப்பட்டு படம் ஆய்வுக்குத் தயாராக்கப்படுகிறது.',
        'உரைநடை, விளிம்பு நடத்தைகள் மற்றும் மீள்தோற்றங்கள் ஆய்வு செய்யப்படுகின்றன.',
        'படம் AI உருவாக்கியதா அல்லது மனிதர் உருவாக்கியதா என்பது கணிக்கப்படுகிறது.',
        'முடிவு நம்பகத்தன்மையுடன் காட்டப்பட்டு வரலாற்றில் சேமிக்கப்படுகிறது.',
      ],
      stackTitle: 'தொழில்நுட்ப குவியல்',
      stack: [
        'React + TypeScript frontend அமைப்புக்காக.',
        'Tailwind CSS பதிலளிக்கும் வடிவமைப்பிற்காக.',
        'Motion அசைவுகள் மற்றும் மாற்றங்களுக்கு.',
        'Express + Multer API மற்றும் பட பதிவேற்ற கையாளுதலுக்காக.',
        'Better SQLite3 வரலாறு சேமிப்பிற்காக.',
        'Gemini API மற்றும் fallback logic வகைப்படுத்தலுக்காக.',
      ],
    },
  },
  hi: {
    navbar: {
      brandSubtitle: 'विजुअल आर्ट डिटेक्शन',
      home: 'होम',
      about: 'परिचय',
      login: 'लॉगिन',
      register: 'रजिस्टर',
      classifier: 'क्लासिफायर',
      history: 'इतिहास',
      themeToggle: 'डार्क मोड बदलें',
      languageLabel: 'भाषा',
      english: 'EN',
      tamil: 'த',
      hindi: 'हि',
    },
    footer: '© 2026 RealLens AI. सर्वाधिकार सुरक्षित।',
    home: {
      badge: 'डीपफेक डिटेक्शन प्लेटफॉर्म',
      title: 'विजुअल आर्ट में डीपफेक',
      description: 'उन्नत Convolutional Neural Networks (CNN) का उपयोग करके AI-निर्मित कला और मानव कला में अंतर करें। किसी कला छवि को अपलोड करके उसकी संरचना और प्रामाणिकता का विश्लेषण करें।',
      startAnalysis: 'विश्लेषण शुरू करें',
      viewRecentResults: 'हाल के परिणाम देखें',
      highlights: [
        { label: 'फोकस', value: 'AI बनाम मानव कला' },
        { label: 'विधि', value: 'CNN आधारित विश्लेषण' },
        { label: 'वर्कफ्लो', value: 'अपलोड, समीक्षा, तुलना' },
      ],
      aboutTitle: 'इस वेबसाइट के बारे में',
      aboutBody: 'यह प्लेटफॉर्म AI-निर्मित कलाकृतियों और मानव-निर्मित कला के बीच अंतर को समझने के लिए बनाया गया है। इसमें इमेज अपलोड, CNN आधारित प्रेडिक्शन, आर्टिफैक्ट निरीक्षण, सेव किया गया इतिहास और एक सहायक चैट अनुभव शामिल है।',
      featureCards: [
        { title: 'प्रामाणिकता', desc: 'जनरेटिव मॉडल में दिखने वाले संरचनात्मक संकेत पहचानें।' },
        { title: 'कलात्मक विश्लेषण', desc: 'ब्रशस्ट्रोक, टेक्सचर फ्लो और कंपोजिशन स्थिरता का विश्लेषण करें।' },
        { title: 'CNN समर्थित', desc: 'मानव कला और सिंथेटिक आउटपुट को अलग करने के लिए डीप फीचर एक्सट्रैक्शन का उपयोग।' },
        { title: 'आसान अपलोड', desc: 'JPG, PNG या WEBP फ़ाइलें अपलोड करें और तुरंत विश्लेषण शुरू करें।' },
        { title: 'आर्टिफैक्ट डिटेक्शन', desc: 'दोहराव पैटर्न, तेज किनारे और असामान्य संकेतों का निरीक्षण करें।' },
        { title: 'स्मार्ट प्रेडिक्शन', desc: 'हर इमेज के लिए AI या मानव परिणाम के साथ कॉन्फिडेंस स्कोर पाएँ।' },
        { title: 'हाल का इतिहास', desc: 'अपने हाल के विश्लेषण परिणाम, समय और फ़ाइल नाम देखें।' },
        { title: 'AI सहायक', desc: 'डीपफेक, CNN विधियों और AI कला नैतिकता पर प्रश्न पूछें।' },
      ],
      classifier: {
        badge: 'विश्लेषण स्टूडियो',
        title: 'आर्ट क्लासिफायर',
        description: 'मानव और AI-निर्मित कला से जुड़े विजुअल संकेतों की तुलना करने के लिए इमेज अपलोड करें। यह टेक्सचर, रिपीटेड पैटर्न, एज स्थिरता और आर्टिफैक्ट संकेतों का निरीक्षण करता है।',
        statCards: [
          { label: 'स्वीकृत फ़ाइलें', value: 'JPG, PNG, WEBP' },
          { label: 'मॉडल फोकस', value: 'CNN फीचर संकेत' },
          { label: 'आउटपुट', value: 'प्रेडिक्शन + कॉन्फिडेंस' },
        ],
        infoCards: [
          { title: 'प्रामाणिक संकेत', desc: 'ब्रश रिद्म, टेक्सचर निरंतरता और संरचनात्मक वास्तविकता की तुलना सिंथेटिक संकेतों से की जाती है।' },
          { title: 'रिसर्च वर्कफ्लो', desc: 'एक ही पैनल में अपलोड करें, निरीक्षण करें, प्रेडिक्शन पाएं और तुलना करें।' },
        ],
        noteTitle: 'क्लासिफायर नोट',
        noteBody: 'स्पष्ट और उच्च गुणवत्ता वाली कला छवियाँ बेहतर परिणाम देती हैं। बेहतर इनपुट से कॉन्फिडेंस स्कोर अधिक अर्थपूर्ण होता है।',
      },
      clearHistoryTitle: 'क्या वर्गीकरण इतिहास साफ़ करें?',
      clearHistoryDescription: 'यह सारा हाल का इतिहास हटा देगा और इसे वापस नहीं लाया जा सकता।',
      clearHistoryConfirm: 'इतिहास साफ़ करें',
      clearHistoryCancel: 'रखें',
    },
    upload: {
      title: 'अपनी कलाकृति यहाँ छोड़ें',
      support: 'JPG, PNG, WEBP समर्थित। 10MB तक की स्पष्ट छवियाँ सर्वोत्तम हैं।',
      chooseImage: 'छवि चुनें',
      chips: ['कैनवास टेक्सचर', 'ब्रशस्ट्रोक फ्लो', 'एज आर्टिफैक्ट'],
      processingTitle: 'न्यूरल फीचर एक्सट्रैक्शन...',
      processingBody: 'ब्रशस्ट्रोक, किनारों और सिंथेटिक संकेतों का विश्लेषण हो रहा है',
      complete: 'विश्लेषण पूर्ण',
      failed: 'अपलोड विफल',
      invalidType: 'अमान्य फ़ाइल प्रकार। कृपया JPG, PNG या WEBP इमेज अपलोड करें।',
      largeFile: 'फ़ाइल बहुत बड़ी है। अधिकतम आकार 10MB है।',
    },
    history: {
      title: 'हाल के वर्गीकरण',
      subtitle: 'हाल के कला विश्लेषण, कॉन्फिडेंस स्तर और प्रेडिक्शन पैटर्न एक ही जगह देखें।',
      empty: 'अभी कोई इतिहास नहीं है। पहले एक कलाकृति अपलोड करें।',
      confidence: 'कॉन्फिडेंस',
      resetLabel: 'वर्गीकरण इतिहास रीसेट करें',
      total: 'कुल आइटम',
      aiCount: 'AI परिणाम',
      humanCount: 'मानव परिणाम',
      latest: 'नवीनतम रन',
      fileLabel: 'फ़ाइल',
      analyzedOn: 'विश्लेषण समय',
    },
    result: {
      uploadedFile: 'अपलोड की गई फ़ाइल',
      summary: 'सारांश',
      analyzedAt: 'विश्लेषण समय',
      confidenceScore: 'कॉन्फिडेंस स्कोर',
      sectionTitle: 'CNN विश्लेषण परिणाम',
      aiSummary: 'सिंथेटिक विशेषताएँ मिलीं',
      humanSummary: 'मानव-निर्मित विशेषताएँ मिलीं',
      fallbackLabel: 'लोकल फॉलबैक विश्लेषण',
      aiExplanation: 'क्लासिफायर ने ऐसे पैटर्न और वितरण संकेत पाए जो आमतौर पर जनरेटेड इमेज से जुड़े होते हैं।',
      humanExplanation: 'क्लासिफायर ने अनियमित टेक्सचर और प्राकृतिक विवरण पाए जो मानव कला के करीब हैं।',
      technicalNote: 'तकनीकी नोट:',
      systemNote: 'सिस्टम नोट:',
      resultReady: 'वर्गीकरण परिणाम तैयार है',
      analysisComplete: 'विश्लेषण पूर्ण',
      file: 'फ़ाइल:',
      timestamp: 'समय:',
    },
    aboutPage: {
      badge: 'मॉडल परिचय',
      title: 'CNN आर्ट डिटेक्शन पाइपलाइन कैसे काम करती है',
      intro: 'यह पेज बताता है कि क्लासिफायर इमेज इनपुट से लेकर फीचर एक्सट्रैक्शन और अंतिम प्रेडिक्शन तक कैसे काम करता है।',
      architectureTitle: 'CNN आर्किटेक्चर अवलोकन',
      architectureBody: 'क्लासिफायर एक चरणबद्ध विजुअल विश्लेषण पाइपलाइन का पालन करता है जो टेक्सचर, कंपोजिशन और आर्टिफैक्ट पैटर्न पर जोर देता है।',
      architectureLayers: [
        { title: 'इनपुट लेयर', desc: 'अपलोड की गई कलाकृति प्राप्त करती है और दृश्य सूचना को सामान्यीकृत करती है।' },
        { title: 'कन्वोल्यूशन ब्लॉक्स', desc: 'किनारे, टेक्सचर और दोहराए जाने वाले संरचनात्मक संकेत निकालते हैं।' },
        { title: 'पूलिंग चरण', desc: 'महत्वपूर्ण पैटर्न रखते हुए स्थानिक विवरण को संकुचित करते हैं।' },
        { title: 'डेंस प्रेडिक्शन लेयर', desc: 'सीखे हुए संकेतों को जोड़कर अंतिम वर्गीकरण और कॉन्फिडेंस देती है।' },
      ],
      stepsTitle: 'यह कैसे काम करता है',
      steps: [
        'क्लासिफायर पैनल से एक कलाकृति इमेज अपलोड करें।',
        'सिस्टम फ़ाइल प्रकार सत्यापित करके इमेज को विश्लेषण के लिए तैयार करता है।',
        'टेक्सचर निरंतरता, एज व्यवहार और दोहराव जैसे संकेतों का निरीक्षण किया जाता है।',
        'क्लासिफायर अनुमान लगाता है कि इमेज AI-निर्मित है या मानव-निर्मित।',
        'अंतिम परिणाम कॉन्फिडेंस के साथ दिखता है और हाल के इतिहास में सेव हो जाता है।',
      ],
      stackTitle: 'टेक स्टैक',
      stack: [
        'फ्रंटएंड संरचना के लिए React + TypeScript।',
        'स्टाइलिंग और रेस्पॉन्सिव लेआउट के लिए Tailwind CSS।',
        'एनिमेशन और ट्रांजिशन के लिए Motion।',
        'API राउटिंग और इमेज अपलोड के लिए Express + Multer।',
        'प्रेडिक्शन इतिहास स्टोरेज के लिए Better SQLite3।',
        'क्लासिफिकेशन आउटपुट के लिए Gemini API और लोकल fallback logic।',
      ],
    },
  },
} as const;

export const getCopy = (language: AppLanguage) => copy[language];